// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"dl/app/taskmanager/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/ana/testsystem/task/create",
				Handler: CreateTaskHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/ana/testsystem/task/delete",
				Handler: DeleteTaskHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/ana/testsystem/task/info",
				Handler: InfoTaskHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/ana/testsystem/task/start",
				Handler: StartTaskHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/ana/testsystem/task/stop",
				Handler: StopTaskHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/ana/testsystem/task/list",
				Handler: ListTaskHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/ana/testsystem/task/update",
				Handler: UpdateTaskHandler(serverCtx),
			},
		},
	)
}
