# 指定Docker Compose文件格式版本
version: '3'

# 定义服务列表
services:
  # MySQL数据库服务
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Iwin-1-321
      MYSQL_DATABASE: hello
      MYSQL_USER: app_user
      MYSQL_PASSWORD: Iwin-1-321
    command:
      --default-authentication-plugin=mysql_native_password
      --max_connections=1000
    restart: always  # 崩溃自动重启
  # Redis缓存服务
  redis:
    image: redis:latest #redis镜像，根据你使用的修改
    # 设置容器名称为bingo-redis
    container_name: bingo-redis
    # 端口映射配置
    ports:
      # 将主机的6379端口映射到容器的6379端口
      - "6379:6379"
    # 网络配置
    networks:
      # 加入自定义网络bingo-network
      - bingo-network

  # etcd服务发现和配置管理服务
  etcd:
    image: gcr.io/etcd-development/etcd:v3.5.16 #etcd镜像
    # 设置容器名称为bingo-etcd
    container_name: bingo-etcd
    # 环境变量配置
    environment:
      # 设置etcd节点名称
      - ETCD_NAME=etcd0
      # 设置etcd数据存储目录
      - ETCD_DATA_DIR=/etcd-data
      # 设置客户端监听地址，监听所有网络接口的2379端口
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      # 设置客户端访问地址，其他服务通过etcd:2379访问
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
      # 设置节点间通信监听地址
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      # 设置节点间通信广播地址
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd:2380
      # 设置初始集群配置
      - ETCD_INITIAL_CLUSTER=etcd0=http://etcd:2380
      # 设置集群令牌，用于区分不同集群
      - ETCD_INITIAL_CLUSTER_TOKEN=etcd-cluster
      # 设置集群初始状态为新建
      - ETCD_INITIAL_CLUSTER_STATE=new
    # 端口映射配置
    ports:
      # 映射客户端访问端口
      - "2379:2379"
      # 映射节点间通信端口
      - "2380:2380"
    # 数据卷挂载配置
    volumes:
      # 将etcd_data卷挂载到容器的/etcd-data目录，实现数据持久化
      - etcd_data:/etcd-data
    # 网络配置
    networks:
      # 加入自定义网络bingo-network
      - bingo-network

  # API服务
  dl-api:
    image: api:latest #你构建的api镜像，使用本地构建的dl-api镜像，根据你的镜像名称和标签修改
    # 设置容器名称为bingo-dl-api
    container_name: bingo-dl-api
    # 端口映射配置
    ports:
      # 将主机的8888端口映射到容器的8888端口
      - "8888:8888"
    # 服务依赖配置，确保redis和etcd先启动
    depends_on:
      # 依赖redis服务
      - redis
      # 依赖etcd服务
      - etcd
    # 环境变量配置
    environment:
      # 设置时区为上海时区
      - TZ=Asia/Shanghai
    # 网络配置
    networks:
      # 加入自定义网络bingo-network
      - bingo-network
    # 重启策略：除非手动停止，否则总是重启
    restart: unless-stopped

  # Python RPC服务
  pyserver:
    image: rpc:latest
    container_name: bingo-pyserver
    ports:
      - "5051:5051" # 确保 server.py 中监听的是 0.0.0.0:5051
    environment:
      - TZ=Asia/Shanghai
      - ETCD_HOST=etcd # <-- 添加环境变量
      - ETCD_PORT=2379 # <-- 添加环境变量
    networks:
      - bingo-network
    restart: unless-stopped


# 数据卷定义
volumes:
  # etcd数据卷，用于持久化etcd数据
  etcd_data:
  mysql_data:


# 网络定义
networks:
  # 自定义网络bingo-network
  bingo-network:
    # 使用bridge驱动，创建桥接网络
    driver: bridge