// Code generated by goctl. DO NOT EDIT.
// Source: dl.proto

package server

import (
	"context"

	"dl/rpc/dl"
	"dl/rpc/internal/logic"
	"dl/rpc/internal/svc"
)

type DLfunctionServer struct {
	svcCtx *svc.ServiceContext
	dl.UnimplementedDLfunctionServer
}

func NewDLfunctionServer(svcCtx *svc.ServiceContext) *DLfunctionServer {
	return &DLfunctionServer{
		svcCtx: svcCtx,
	}
}

func (s *DLfunctionServer) GetDLById(ctx context.Context, in *dl.DLGetRequestById) (*dl.DLGetResponseById, error) {
	l := logic.NewGetDLByIdLogic(ctx, s.svcCtx)
	return l.GetDLById(in)
}

func (s *DLfunctionServer) CreateDL(ctx context.Context, in *dl.DLCreateRequest) (*dl.DLCreateResponse, error) {
	l := logic.NewCreateDLLogic(ctx, s.svcCtx)
	return l.CreateDL(in)
}

func (s *DLfunctionServer) InitDL(ctx context.Context, in *dl.DLapp) (*dl.DLapp, error) {
	l := logic.NewInitDLLogic(ctx, s.svcCtx)
	return l.InitDL(in)
}

func (s *DLfunctionServer) InitDLModel(ctx context.Context, in *dl.SetDLModelRequest) (*dl.DLModel, error) {
	l := logic.NewInitDLModelLogic(ctx, s.svcCtx)
	return l.InitDLModel(in)
}

func (s *DLfunctionServer) InitDLData(ctx context.Context, in *dl.SetDLDataRequest) (*dl.DLDataOBJ, error) {
	l := logic.NewInitDLDataLogic(ctx, s.svcCtx)
	return l.InitDLData(in)
}
