// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.4

package types

type DLApp struct {
	Metadata DLMetadata `json:"metadata"`
	Spec     DLSpec     `json:"spec"`
}

type DLCreateRequest struct {
	Namespace string `json:"namespace"`
	DLName    string `json:"dlname"`
	Spec      DLSpec `json:"spec"`
}

type DLCreateResponse struct {
	DLInfo DLApp `json:"dlinfo"`
}

type DLData struct {
	Index  string `json:"index,omitempty"`
	Status bool   `json:"status,omitempty"` // 该数据是否可用
	Deal   string `json:"deal,omitempty"`   // 该数据结束到哪个流程了，后面这个要变成枚举
}

type DLDataOBJ struct {
	Database string `json:"database,omitempty"`
	Name     string `json:"name,omitempty"`
	Status   bool   `json:"status,omitempty"` // 该数据对象是否可用
	Total    int64  `json:"total,omitempty"`
	Type     string `json:"type,omitempty"`
}

type DLGetRequest struct {
	Id string `form:"id"`
}

type DLGetResponse struct {
	DL DLApp `json:"DL"`
}

type DLMetadata struct {
	Id        string `json:"id"`
	Namespace string `json:"namespace"`
	DLName    string `json:"dlname"`
}

type DLModel struct {
	Name       string `json:"dlmodelname"`
	Path       string `json:"dlmodelpath,omitempty"`
	Status     bool   `json:"dlmodelstatus,omitempty"` //模型是否可用
	InputType  string `json:"dlinput,omitempty"`
	OutputType string `json:"dloutput,omitempty"`
}

type DLSpec struct {
	Model DLModel   `json:"dlmodel"`
	Data  DLDataOBJ `json:"dldataobj,omitempty"`
}
