// Code generated by goctl. DO NOT EDIT.
package types

type DL struct {
	Metadata DLMetadata `json:"metadata"`
	Spec     DLSpec     `json:"spec"`
}

type DLMetadata struct {
	Id      string `json:"id"`
	Builder string `json:"builder"`
	DLName  string `json:"dlname"`
}

type DLSpec struct {
	Model  DLModel  `json:"dlmodel"`
	Data   []DLData `json:"dldata"`
	Laster DLData   `json:"laster"`
}

type DLModel struct {
	Name       string `json:"dlmodelname"`
	Path       string `json:"dlmodelpath"`
	Status     bool   `json:"dlmodelstatus"` //模型是否可用
	InputType  string `json:"dlinput"`
	OutputType string `json:"dloutput"`
}

type DLData struct {
	Index  string `json:"dataindex"`
	Status bool   `json:"datastatus"` //该数据是否可用
	Deal   string `json:"datadeal"`   //该数据结束到哪个流程了，后面这个要变成枚举
	Type   string `json:"datatype"`
}

type DLGetRequest struct {
	Id string `json:"id"`
}

type DLGetResponse struct {
	DL DL `json:"DL"`
}

type DLCreateRequest struct {
	Spec DLSpec `json:"spec"`
}

type DLCreateResponse struct {
	Metadata DLMetadata `json:"metadata"`
}
