// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"dl/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/dl/api/get",
				Handler: GetDLHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/dl/api/create",
				Handler: CreateDLHandler(serverCtx),
			},
		},
	)
}
