// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v3.19.4
// source: model.proto

package modeler

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DLModel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Path       string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Status     bool   `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"` // 模型是否可用
	InputType  string `protobuf:"bytes,4,opt,name=inputType,proto3" json:"inputType,omitempty"`
	OutputType string `protobuf:"bytes,5,opt,name=outputType,proto3" json:"outputType,omitempty"`
}

func (x *DLModel) Reset() {
	*x = DLModel{}
	mi := &file_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DLModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DLModel) ProtoMessage() {}

func (x *DLModel) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DLModel.ProtoReflect.Descriptor instead.
func (*DLModel) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{0}
}

func (x *DLModel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DLModel) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *DLModel) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *DLModel) GetInputType() string {
	if x != nil {
		return x.InputType
	}
	return ""
}

func (x *DLModel) GetOutputType() string {
	if x != nil {
		return x.OutputType
	}
	return ""
}

type DLDataOBJ struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Database string `protobuf:"bytes,1,opt,name=Database,proto3" json:"Database,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status   bool   `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"` // 该数据对象是否可用
	Total    int64  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	Type     string `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *DLDataOBJ) Reset() {
	*x = DLDataOBJ{}
	mi := &file_model_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DLDataOBJ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DLDataOBJ) ProtoMessage() {}

func (x *DLDataOBJ) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DLDataOBJ.ProtoReflect.Descriptor instead.
func (*DLDataOBJ) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{1}
}

func (x *DLDataOBJ) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *DLDataOBJ) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DLDataOBJ) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *DLDataOBJ) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *DLDataOBJ) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type DLData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index  string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
	Status bool   `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"` // 该数据是否可用
	Deal   string `protobuf:"bytes,3,opt,name=deal,proto3" json:"deal,omitempty"`      // 该数据结束到哪个流程了，后面这个要变成枚举
}

func (x *DLData) Reset() {
	*x = DLData{}
	mi := &file_model_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DLData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DLData) ProtoMessage() {}

func (x *DLData) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DLData.ProtoReflect.Descriptor instead.
func (*DLData) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{2}
}

func (x *DLData) GetIndex() string {
	if x != nil {
		return x.Index
	}
	return ""
}

func (x *DLData) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *DLData) GetDeal() string {
	if x != nil {
		return x.Deal
	}
	return ""
}

type SetDLModelRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *SetDLModelRequest) Reset() {
	*x = SetDLModelRequest{}
	mi := &file_model_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDLModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDLModelRequest) ProtoMessage() {}

func (x *SetDLModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDLModelRequest.ProtoReflect.Descriptor instead.
func (*SetDLModelRequest) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{3}
}

func (x *SetDLModelRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type SetDLDataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Database string `protobuf:"bytes,1,opt,name=Database,proto3" json:"Database,omitempty"`
}

func (x *SetDLDataRequest) Reset() {
	*x = SetDLDataRequest{}
	mi := &file_model_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDLDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDLDataRequest) ProtoMessage() {}

func (x *SetDLDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_model_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDLDataRequest.ProtoReflect.Descriptor instead.
func (*SetDLDataRequest) Descriptor() ([]byte, []int) {
	return file_model_proto_rawDescGZIP(), []int{4}
}

func (x *SetDLDataRequest) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

var File_model_proto protoreflect.FileDescriptor

var file_model_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x65, 0x72, 0x22, 0x87, 0x01, 0x0a, 0x07, 0x44, 0x4c, 0x4d, 0x6f, 0x64,
	0x65, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x1e, 0x0a, 0x0a, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x54, 0x79, 0x70, 0x65,
	0x22, 0x7d, 0x0a, 0x09, 0x44, 0x4c, 0x44, 0x61, 0x74, 0x61, 0x4f, 0x42, 0x4a, 0x12, 0x1a, 0x0a,
	0x08, 0x44, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x44, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22,
	0x4a, 0x0a, 0x06, 0x44, 0x4c, 0x44, 0x61, 0x74, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64,
	0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x65, 0x61, 0x6c, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x65, 0x61, 0x6c, 0x22, 0x27, 0x0a, 0x11, 0x73,
	0x65, 0x74, 0x44, 0x4c, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x70, 0x61, 0x74, 0x68, 0x22, 0x2e, 0x0a, 0x10, 0x73, 0x65, 0x74, 0x44, 0x4c, 0x44, 0x61, 0x74,
	0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x44, 0x61, 0x74, 0x61,
	0x62, 0x61, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x44, 0x61, 0x74, 0x61,
	0x62, 0x61, 0x73, 0x65, 0x32, 0x85, 0x01, 0x0a, 0x09, 0x44, 0x4c, 0x4d, 0x6f, 0x64, 0x65, 0x6c,
	0x65, 0x72, 0x12, 0x3b, 0x0a, 0x0b, 0x69, 0x6e, 0x69, 0x74, 0x44, 0x4c, 0x4d, 0x6f, 0x64, 0x65,
	0x6c, 0x12, 0x1a, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x65, 0x72, 0x2e, 0x73, 0x65, 0x74, 0x44,
	0x4c, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e,
	0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x65, 0x72, 0x2e, 0x44, 0x4c, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12,
	0x3b, 0x0a, 0x0a, 0x69, 0x6e, 0x69, 0x74, 0x44, 0x4c, 0x44, 0x61, 0x74, 0x61, 0x12, 0x19, 0x2e,
	0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x65, 0x72, 0x2e, 0x73, 0x65, 0x74, 0x44, 0x4c, 0x44, 0x61, 0x74,
	0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x65, 0x72, 0x2e, 0x44, 0x4c, 0x44, 0x61, 0x74, 0x61, 0x4f, 0x42, 0x4a, 0x42, 0x0b, 0x5a, 0x09,
	0x2e, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_model_proto_rawDescOnce sync.Once
	file_model_proto_rawDescData = file_model_proto_rawDesc
)

func file_model_proto_rawDescGZIP() []byte {
	file_model_proto_rawDescOnce.Do(func() {
		file_model_proto_rawDescData = protoimpl.X.CompressGZIP(file_model_proto_rawDescData)
	})
	return file_model_proto_rawDescData
}

var file_model_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_model_proto_goTypes = []any{
	(*DLModel)(nil),           // 0: modeler.DLModel
	(*DLDataOBJ)(nil),         // 1: modeler.DLDataOBJ
	(*DLData)(nil),            // 2: modeler.DLData
	(*SetDLModelRequest)(nil), // 3: modeler.setDLModelRequest
	(*SetDLDataRequest)(nil),  // 4: modeler.setDLDataRequest
}
var file_model_proto_depIdxs = []int32{
	3, // 0: modeler.DLModeler.initDLModel:input_type -> modeler.setDLModelRequest
	4, // 1: modeler.DLModeler.initDLData:input_type -> modeler.setDLDataRequest
	0, // 2: modeler.DLModeler.initDLModel:output_type -> modeler.DLModel
	1, // 3: modeler.DLModeler.initDLData:output_type -> modeler.DLDataOBJ
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_model_proto_init() }
func file_model_proto_init() {
	if File_model_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_model_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_model_proto_goTypes,
		DependencyIndexes: file_model_proto_depIdxs,
		MessageInfos:      file_model_proto_msgTypes,
	}.Build()
	File_model_proto = out.File
	file_model_proto_rawDesc = nil
	file_model_proto_goTypes = nil
	file_model_proto_depIdxs = nil
}
