// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.4
// source: model.proto

package modeler

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DLModeler_InitDLModel_FullMethodName = "/modeler.DLModeler/initDLModel"
	DLModeler_InitDLData_FullMethodName  = "/modeler.DLModeler/initDLData"
)

// DLModelerClient is the client API for DLModeler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DLModelerClient interface {
	InitDLModel(ctx context.Context, in *SetDLModelRequest, opts ...grpc.CallOption) (*DLModel, error)
	InitDLData(ctx context.Context, in *SetDLDataRequest, opts ...grpc.CallOption) (*DLDataOBJ, error)
}

type dLModelerClient struct {
	cc grpc.ClientConnInterface
}

func NewDLModelerClient(cc grpc.ClientConnInterface) DLModelerClient {
	return &dLModelerClient{cc}
}

func (c *dLModelerClient) InitDLModel(ctx context.Context, in *SetDLModelRequest, opts ...grpc.CallOption) (*DLModel, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DLModel)
	err := c.cc.Invoke(ctx, DLModeler_InitDLModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dLModelerClient) InitDLData(ctx context.Context, in *SetDLDataRequest, opts ...grpc.CallOption) (*DLDataOBJ, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DLDataOBJ)
	err := c.cc.Invoke(ctx, DLModeler_InitDLData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DLModelerServer is the server API for DLModeler service.
// All implementations must embed UnimplementedDLModelerServer
// for forward compatibility.
type DLModelerServer interface {
	InitDLModel(context.Context, *SetDLModelRequest) (*DLModel, error)
	InitDLData(context.Context, *SetDLDataRequest) (*DLDataOBJ, error)
	mustEmbedUnimplementedDLModelerServer()
}

// UnimplementedDLModelerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDLModelerServer struct{}

func (UnimplementedDLModelerServer) InitDLModel(context.Context, *SetDLModelRequest) (*DLModel, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitDLModel not implemented")
}
func (UnimplementedDLModelerServer) InitDLData(context.Context, *SetDLDataRequest) (*DLDataOBJ, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitDLData not implemented")
}
func (UnimplementedDLModelerServer) mustEmbedUnimplementedDLModelerServer() {}
func (UnimplementedDLModelerServer) testEmbeddedByValue()                   {}

// UnsafeDLModelerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DLModelerServer will
// result in compilation errors.
type UnsafeDLModelerServer interface {
	mustEmbedUnimplementedDLModelerServer()
}

func RegisterDLModelerServer(s grpc.ServiceRegistrar, srv DLModelerServer) {
	// If the following call pancis, it indicates UnimplementedDLModelerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DLModeler_ServiceDesc, srv)
}

func _DLModeler_InitDLModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetDLModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DLModelerServer).InitDLModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DLModeler_InitDLModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DLModelerServer).InitDLModel(ctx, req.(*SetDLModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DLModeler_InitDLData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetDLDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DLModelerServer).InitDLData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DLModeler_InitDLData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DLModelerServer).InitDLData(ctx, req.(*SetDLDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DLModeler_ServiceDesc is the grpc.ServiceDesc for DLModeler service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DLModeler_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "modeler.DLModeler",
	HandlerType: (*DLModelerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "initDLModel",
			Handler:    _DLModeler_InitDLModel_Handler,
		},
		{
			MethodName: "initDLData",
			Handler:    _DLModeler_InitDLData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "model.proto",
}
