# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dl.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'dl.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08\x64l.proto\x12\x02\x64l\"C\n\x05\x44Lapp\x12 \n\x08metadata\x18\x01 \x01(\x0b\x32\x0e.dl.DLMetadata\x12\x18\n\x04spec\x18\x02 \x01(\x0b\x32\n.dl.DLSpec\";\n\nDLMetadata\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\tNamespace\x18\x02 \x01(\t\x12\x0e\n\x06\x44LName\x18\x03 \x01(\t\"D\n\x06\x44LSpec\x12\x1a\n\x05model\x18\x01 \x01(\x0b\x32\x0b.dl.DLModel\x12\x1e\n\x07\x64\x61taObj\x18\x02 \x01(\x0b\x32\r.dl.DLDataOBJ\"D\n\x0c\x44LCreateSpec\x12\x11\n\tNamespace\x18\x01 \x01(\t\x12\x0e\n\x06\x44LName\x18\x02 \x01(\t\x12\x11\n\tmodelName\x18\x03 \x01(\t\"\\\n\x07\x44LModel\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04path\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\x08\x12\x11\n\tinputType\x18\x04 \x01(\t\x12\x12\n\noutputType\x18\x05 \x01(\t\"X\n\tDLDataOBJ\x12\x10\n\x08\x44\x61tabase\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\x08\x12\r\n\x05total\x18\x04 \x01(\x03\x12\x0c\n\x04type\x18\x05 \x01(\t\"5\n\x06\x44LData\x12\r\n\x05index\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\x08\x12\x0c\n\x04\x64\x65\x61l\x18\x03 \x01(\t\"\x1e\n\x10\x44LGetRequestById\x12\n\n\x02id\x18\x01 \x01(\t\"-\n\x11\x44LGetResponseById\x12\x18\n\x05\x64lApp\x18\x01 \x01(\x0b\x32\t.dl.DLapp\"1\n\x0f\x44LCreateRequest\x12\x1e\n\x04spec\x18\x01 \x01(\x0b\x32\x10.dl.DLCreateSpec\",\n\x10\x44LCreateResponse\x12\x18\n\x05\x64lApp\x18\x01 \x01(\x0b\x32\t.dl.DLapp\"!\n\x11setDLModelRequest\x12\x0c\n\x04path\x18\x01 \x01(\t\"$\n\x10setDLDataRequest\x12\x10\n\x08\x44\x61tabase\x18\x01 \x01(\t2\x9f\x01\n\nDLfunction\x12\x38\n\tgetDLById\x12\x14.dl.DLGetRequestById\x1a\x15.dl.DLGetResponseById\x12\x37\n\x08\x63reateDL\x12\x13.dl.DLCreateRequest\x1a\x14.dl.DLCreateResponse\"\x00\x12\x1e\n\x06initDL\x12\t.dl.DLapp\x1a\t.dl.DLappB\x06Z\x04./dlb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dl_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\004./dl'
  _globals['_DLAPP']._serialized_start=16
  _globals['_DLAPP']._serialized_end=83
  _globals['_DLMETADATA']._serialized_start=85
  _globals['_DLMETADATA']._serialized_end=144
  _globals['_DLSPEC']._serialized_start=146
  _globals['_DLSPEC']._serialized_end=214
  _globals['_DLCREATESPEC']._serialized_start=216
  _globals['_DLCREATESPEC']._serialized_end=284
  _globals['_DLMODEL']._serialized_start=286
  _globals['_DLMODEL']._serialized_end=378
  _globals['_DLDATAOBJ']._serialized_start=380
  _globals['_DLDATAOBJ']._serialized_end=468
  _globals['_DLDATA']._serialized_start=470
  _globals['_DLDATA']._serialized_end=523
  _globals['_DLGETREQUESTBYID']._serialized_start=525
  _globals['_DLGETREQUESTBYID']._serialized_end=555
  _globals['_DLGETRESPONSEBYID']._serialized_start=557
  _globals['_DLGETRESPONSEBYID']._serialized_end=602
  _globals['_DLCREATEREQUEST']._serialized_start=604
  _globals['_DLCREATEREQUEST']._serialized_end=653
  _globals['_DLCREATERESPONSE']._serialized_start=655
  _globals['_DLCREATERESPONSE']._serialized_end=699
  _globals['_SETDLMODELREQUEST']._serialized_start=701
  _globals['_SETDLMODELREQUEST']._serialized_end=734
  _globals['_SETDLDATAREQUEST']._serialized_start=736
  _globals['_SETDLDATAREQUEST']._serialized_end=772
  _globals['_DLFUNCTION']._serialized_start=775
  _globals['_DLFUNCTION']._serialized_end=934
# @@protoc_insertion_point(module_scope)
