# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import dl_pb2 as dl__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in dl_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DLfunctionStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getDLById = channel.unary_unary(
                '/dl.DLfunction/getDLById',
                request_serializer=dl__pb2.DLGetRequestById.SerializeToString,
                response_deserializer=dl__pb2.DLGetResponseById.FromString,
                _registered_method=True)
        self.createDL = channel.unary_unary(
                '/dl.DLfunction/createDL',
                request_serializer=dl__pb2.DLCreateRequest.SerializeToString,
                response_deserializer=dl__pb2.DLCreateResponse.FromString,
                _registered_method=True)
        self.initDL = channel.unary_unary(
                '/dl.DLfunction/initDL',
                request_serializer=dl__pb2.DLapp.SerializeToString,
                response_deserializer=dl__pb2.DLapp.FromString,
                _registered_method=True)


class DLfunctionServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getDLById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def createDL(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def initDL(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DLfunctionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getDLById': grpc.unary_unary_rpc_method_handler(
                    servicer.getDLById,
                    request_deserializer=dl__pb2.DLGetRequestById.FromString,
                    response_serializer=dl__pb2.DLGetResponseById.SerializeToString,
            ),
            'createDL': grpc.unary_unary_rpc_method_handler(
                    servicer.createDL,
                    request_deserializer=dl__pb2.DLCreateRequest.FromString,
                    response_serializer=dl__pb2.DLCreateResponse.SerializeToString,
            ),
            'initDL': grpc.unary_unary_rpc_method_handler(
                    servicer.initDL,
                    request_deserializer=dl__pb2.DLapp.FromString,
                    response_serializer=dl__pb2.DLapp.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dl.DLfunction', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dl.DLfunction', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DLfunction(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getDLById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dl.DLfunction/getDLById',
            dl__pb2.DLGetRequestById.SerializeToString,
            dl__pb2.DLGetResponseById.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def createDL(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dl.DLfunction/createDL',
            dl__pb2.DLCreateRequest.SerializeToString,
            dl__pb2.DLCreateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def initDL(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dl.DLfunction/initDL',
            dl__pb2.DLapp.SerializeToString,
            dl__pb2.DLapp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
