# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import model_pb2 as model__pb2

GRPC_GENERATED_VERSION = '1.67.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in model_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DLModelerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.initDLModel = channel.unary_unary(
                '/modeler.DLModeler/initDLModel',
                request_serializer=model__pb2.setDLModelRequest.SerializeToString,
                response_deserializer=model__pb2.DLModel.FromString,
                _registered_method=True)
        self.initDLData = channel.unary_unary(
                '/modeler.DLModeler/initDLData',
                request_serializer=model__pb2.setDLDataRequest.SerializeToString,
                response_deserializer=model__pb2.DLDataOBJ.FromString,
                _registered_method=True)


class DLModelerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def initDLModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def initDLData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DLModelerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'initDLModel': grpc.unary_unary_rpc_method_handler(
                    servicer.initDLModel,
                    request_deserializer=model__pb2.setDLModelRequest.FromString,
                    response_serializer=model__pb2.DLModel.SerializeToString,
            ),
            'initDLData': grpc.unary_unary_rpc_method_handler(
                    servicer.initDLData,
                    request_deserializer=model__pb2.setDLDataRequest.FromString,
                    response_serializer=model__pb2.DLDataOBJ.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'modeler.DLModeler', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('modeler.DLModeler', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DLModeler(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def initDLModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/modeler.DLModeler/initDLModel',
            model__pb2.setDLModelRequest.SerializeToString,
            model__pb2.DLModel.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def initDLData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/modeler.DLModeler/initDLData',
            model__pb2.setDLDataRequest.SerializeToString,
            model__pb2.DLDataOBJ.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
