# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: model.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'model.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bmodel.proto\x12\x07modeler\"\\\n\x07\x44LModel\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04path\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\x08\x12\x11\n\tinputType\x18\x04 \x01(\t\x12\x12\n\noutputType\x18\x05 \x01(\t\"X\n\tDLDataOBJ\x12\x10\n\x08\x44\x61tabase\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\x08\x12\r\n\x05total\x18\x04 \x01(\x03\x12\x0c\n\x04type\x18\x05 \x01(\t\"5\n\x06\x44LData\x12\r\n\x05index\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\x08\x12\x0c\n\x04\x64\x65\x61l\x18\x03 \x01(\t\"!\n\x11setDLModelRequest\x12\x0c\n\x04path\x18\x01 \x01(\t\"$\n\x10setDLDataRequest\x12\x10\n\x08\x44\x61tabase\x18\x01 \x01(\t2\x85\x01\n\tDLModeler\x12;\n\x0binitDLModel\x12\x1a.modeler.setDLModelRequest\x1a\x10.modeler.DLModel\x12;\n\ninitDLData\x12\x19.modeler.setDLDataRequest\x1a\x12.modeler.DLDataOBJB\x0bZ\t./modelerb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'model_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\t./modeler'
  _globals['_DLMODEL']._serialized_start=24
  _globals['_DLMODEL']._serialized_end=116
  _globals['_DLDATAOBJ']._serialized_start=118
  _globals['_DLDATAOBJ']._serialized_end=206
  _globals['_DLDATA']._serialized_start=208
  _globals['_DLDATA']._serialized_end=261
  _globals['_SETDLMODELREQUEST']._serialized_start=263
  _globals['_SETDLMODELREQUEST']._serialized_end=296
  _globals['_SETDLDATAREQUEST']._serialized_start=298
  _globals['_SETDLDATAREQUEST']._serialized_end=334
  _globals['_DLMODELER']._serialized_start=337
  _globals['_DLMODELER']._serialized_end=470
# @@protoc_insertion_point(module_scope)
