// Code generated by goctl. DO NOT EDIT.
// Source: model.proto

package server

import (
	"context"

	"dl/rpc/model/internal/logic"
	"dl/rpc/model/internal/svc"
	"dl/rpc/model/modeler"
)

type DLModelerServer struct {
	svcCtx *svc.ServiceContext
	modeler.UnimplementedDLModelerServer
}

func NewDLModelerServer(svcCtx *svc.ServiceContext) *DLModelerServer {
	return &DLModelerServer{
		svcCtx: svcCtx,
	}
}

func (s *DLModelerServer) InitDLModel(ctx context.Context, in *modeler.SetDLModelRequest) (*modeler.DLModel, error) {
	l := logic.NewInitDLModelLogic(ctx, s.svcCtx)
	return l.InitDLModel(in)
}

func (s *DLModelerServer) InitDLData(ctx context.Context, in *modeler.SetDLDataRequest) (*modeler.DLDataOBJ, error) {
	l := logic.NewInitDLDataLogic(ctx, s.svcCtx)
	return l.InitDLData(in)
}
