// Code generated by goctl. DO NOT EDIT.
package types

type SceneInfo struct {
	Index       string   `json:"index"`
	Type        string   `json:"type"`
	Name        string   `json:"name"`
	ModelMaster string   `json:"model_master"`
	ModelSlave  []string `json:"model_slave"`
	Algorithm   []string `json:"algorithm"`
	Alarm       []string `json:"alarm"`
}

type DatasetInfo struct {
	DatasetId   string     `json:"datasetId"`
	DatasetName string     `json:"datasetName"`
	Namespace   string     `json:"namespace"`
	Dataset     []dataInfo `json:"dataset"`
}

type DataInfo struct {
	Url   string `json:"url"`
	Name  string `json:"name"`
	Type  string `json:"type"`
	Label string `json:"label"`
}

type TaskMetaData struct {
	TaskID          string `json:"taskID"`
	TaskName        string `json:"taskName"`
	CreateTimeStamp string `json:"createTimeStamp"`
	CreateUser      string `json:"createUser"`
}

type TaskCreateRequest struct {
	Id          string      `json:"id"`
	Name        string      `json:"name"`
	SceneInfo   sceneInfo   `json:"sceneInfo"`
	DatasetInfo datasetInfo `json:"datasetInfo"`
	CreateUser  string      `json:"createUser"`
}

type TaskCreateResponse struct {
	TaskMetaData taskMetaData `json:"taskMetaData"`
}

type TaskDeleteRequest struct {
	Id string `json:"id"`
}

type TaskDeleteResponse struct {
	TaskMetaData taskMetaData `json:"taskMetaData"`
}

type TaskInfoRequest struct {
	Id string `json:"id"`
}

type TaskInfoResponse struct {
	TaskMetaData taskMetaData `json:"taskMetaData"`
	Status       string       `json:"status"`
}

type TaskStartRequest struct {
	Id string `json:"id"`
}

type TaskStartResponse struct {
	TaskMetaData taskMetaData `json:"taskMetaData"`
	Status       string       `json:"status"`
}

type TaskStopRequest struct {
	Id string `json:"id"`
}

type TaskStopResponse struct {
	TaskMetaData taskMetaData `json:"taskMetaData"`
	Status       string       `json:"status"`
}

type TaskListResponse struct {
	Tasks []taskInfo `json:"tasks"`
}

type TaskInfo struct {
	Id           string       `json:"id"`
	Name         string       `json:"name"`
	SceneInfo    sceneInfo    `json:"sceneInfo"`
	DatasetInfo  datasetInfo  `json:"datasetInfo"`
	Status       string       `json:"status"`
	TaskMetaData taskMetaData `json:"taskMetaData"`
}

type TaskUpdateRequest struct {
	Id          string      `json:"id"`
	Name        string      `json:"name"`
	SceneInfo   sceneInfo   `json:"sceneInfo"`
	DatasetInfo datasetInfo `json:"datasetInfo"`
}

type TaskUpdateResponse struct {
	TaskMetaData taskMetaData `json:"taskMetaData"`
}
